# vim: filetype=sh
## ~/.bash_aliases
## Used for added alias definitions
# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.


####################
### My Aliases
####################

alias playground-terminal='cd ~/Desktop/PLAYGROUND_TERMINAL/'
alias nmr='sudo service network-manager restart'

# usb related ------------------------------------------------------------------
alias usbstick="cd /run/media/$USER/BIEWESCH_K/"
alias gvimportable="/run/media/$USER/BIEWESCH_K/gVimPortable7.4/gVimPortable.exe"

# mount related ----------------------------------------------------------------
alias go-mtp="cd /run/user/$UID/gvfs"

#alias nvlc='nvlc --no-color'
alias l1='ls -1'
alias sl='sl -ae'

# Windows applications ---------------------------------------------------------
# alias cmd='/home/kevin/.wine/dosdevices/c:/windows/command/start.exe' 
# alias delphi6-windows='/home/kevin/.wine/dosdevices/c:/Program\ Files\ \(x86\)/Borland/Delphi6/Bin/delphi32.exe'

# vim shortcut -----------------------------------------------------------------
alias v='vim'
alias n='nvim'

# tmux shortcut ----------------------------------------------------------------
alias t='tmux'
alias tl='tmux ls'
alias ta='tmux attach'
alias tat='tmux attach -t'
alias tn='tmux new -s'
alias tk='tmux kill-session -t'
# alias tr='~/.tmux/plugins/tmux-resurrect/scripts/restore.sh'

# herbstclient -----------------------------------------------------------------
alias hc="herbstclient"

# alias vagrant='~/BSP/Semester_1/Vagrant_VM/missaleneous/Vagrant_download/vagrant'

# Lazy -------------------------------------------------------------------------
alias lg='lazygit'
alias lzd='lazydocker'

# git alias for dotfiles -------------------------------------------------------
alias config='git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias config-s='config status'
alias config-a='config add'
alias config-c='config commit -m'
alias config-C='config commit -a -m'
alias config-p='config push'

# feh --------------------------------------------------------------------------
alias feh='feh -Z --scale-down'

# Jupyter ----------------------------------------------------------------------
alias jn='jupyter-notebook'

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                  University
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# get faster to the uni folders ------------------------------------------------
alias mc='cd /home/kuni/University/Master/semester_3/Computer-Vision-and-Image-Analysis && lfcd'
alias mb='cd /home/kuni/University/Master/semester_3/CubeSatLab-Build-I && lfcd'
alias me='cd /home/kuni/University/Master/semester_3/Entrepreneurship && lfcd'
alias mg='cd /home/kuni/University/Master/semester_3/GNSS-Theory-and-Application && lfcd'
alias ml='cd /home/kuni/University/Master/semester_3/Machine-Learning-Space-Master && lfcd'
alias ma='cd /home/kuni/University/Master/semester_3/Practical-Aspects-of-Entrepreneurship && lfcd'
alias ms='cd /home/kuni/University/Master/semester_3/Scientific-Space-Project && lfcd'
alias mr='cd /home/kuni/University/Master/semester_3/Robotic-Manipulation-in-Space/ && lfcd'

# alias mj='cd /home/kuni/University/Master/SummerJob && lfcd'
# alias mjn='cd /home/kuni/University/Master/SummerJob/notes && lfcd'
# alias mjr='cd /home/kuni/University/Master/SummerJob/resources && lfcd'
# alias mjc='cd /home/kuni/University/Master/SummerJob/code && lfcd'

# # swift aliases ----------------------------------------------------------------
# alias sb='swift build'
# alias sr='swift run'
# alias se='swift build && swift run'

# # get faster to erasmus stuff --------------------------------------------------
# alias ew='cd /home/kuni/University/Bachelor/semester_4/Erasmus/wohnung'
# alias em='cd /home/kuni/University/Bachelor/semester_4/Erasmus/Miscellaneous'
# alias el='cd /home/kuni/University/Bachelor/semester_4/Erasmus/Learning_Agreement'


# # TU Wien directories ---------------------------------------------------------
# alias tu='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN && lfcd'
# alias tua='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/Articial_Intelligence && lfcd'
# alias tuv='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/Visual_Computing && lfcd'
# alias tuc='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/Compilers && lfcd'
# alias tup='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/SEPM-VO && lfcd'
# alias tuP='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/SEPM-PR/QSE-Gruppenphase/Source-Project && lfcd'
# alias tus='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/Security-VU && lfcd'
# alias tuS='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/Security-UE && lfcd'

# # SEPM --------------------------------------------------------------------------
# alias sf='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/SEPM-PR/QSE-Gruppenphase/Source-Project/ss20_sepm_qse_14/frontend/'
# alias sb='cd /home/kuni/University/Bachelor/semester_4/TU-WIEN/SEPM-PR/QSE-Gruppenphase/Source-Project/ss20_sepm_qse_14/backend/'

# alias rb='(sb && mvn clean compile && mvn spring-boot:run)'
# alias rd='(sb && rm -rf database && mvn clean compile && mvn spring-boot:run -Dspring-boot.run.profiles=datagen)'
# alias rt='(cd "$(git rev-parse --show-toplevel)/backend" && mvn clean compile && mvn clean test)'

# alias rf='(sf && ng serve)'

# vpn for testbed security server ----------------------------------------------
# alias svpn='sudo openvpn ~/University/Bachelor/semester_4/TU-WIEN/Security-UE/wutctf.ovpn'

# run ssh commmands for compiler server ----------------------------------------
# alias cs='clear && ssh -tq complang'
