defaultIndent: "  "

indentAfterHeadings:
  part:
    indentAfterThisHeading: 1
  chapter:
    indentAfterThisHeading: 1
  section:
    indentAfterThisHeading: 1
  subsection:
    indentAfterThisHeading: 1
  subsection*:
    indentAfterThisHeading: 1
  subsubsection:
    indentAfterThisHeading: 1
  paragraph:
    indentAfterThisHeading: 1
  subparagraph:
    indentAfterThisHeading: 1

onlyOneBackUp: 1
maxNumberOfBackups: 3

# verbatimCommands:
#   verb: 1
#   lstinline: 1
#   mintinline:
#     name: '\\mintinline\{\w+\}'
#     lookForThis: 1

verbatimCommands:
  nameAsRegex:
  name: ’\w+inline’
  lookForThis: 1

modifyLineBreaks:
  condenseMultipleBlankLinesInto: 2
  textWrapOptions:
    columns: 70
    # when: after  # fixed in V 3.22.1 (2023-07-02) https://github.com/cmhughes/latexindent.pl/issues/450
    blocksFollow:
      headings: 0
      # commentOnPreviousLine: 1
      # commentOnOwnLine: 0
  environments:
    BeginStartsOnOwnLine: 2
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 3
    EndFinishesWithLineBreak: 0
    tabular:
      EndStartsOnOwnLine: 0
    tblr:
      EndStartsOnOwnLine: 0
    block: # beamer
      BodyStartsOnOwnLine: 0
    alertblock: # beamer
      BodyStartsOnOwnLine: 0
    exampleblock: # beamer
      BodyStartsOnOwnLine: 0
    theorem: # beamer
      BodyStartsOnOwnLine: 0
    definition: # beamer
      BodyStartsOnOwnLine: 0
    example: # beamer
      BodyStartsOnOwnLine: 0
    proof: # beamer
      BodyStartsOnOwnLine: 0
    beamercolorbox: # beamer
      BodyStartsOnOwnLine: 0
    beamerboxesrounded: # beamer
      BodyStartsOnOwnLine: 0
    columns: # beamer
      BodyStartsOnOwnLine: 0
    column: # beamer
      BodyStartsOnOwnLine: 0
    abstract: # beamer
      BodyStartsOnOwnLine: 0
    verse: # beamer
      BodyStartsOnOwnLine: 0
    quotation: # beamer
      BodyStartsOnOwnLine: 0
    quote: # beamer
      BodyStartsOnOwnLine: 0
    frame: # beamer
      BodyStartsOnOwnLine: 0
    onlyenv: # beamer
      BodyStartsOnOwnLine: 0
    altenv: # beamer
      BodyStartsOnOwnLine: 0
    visibleenv: # beamer
      BodyStartsOnOwnLine: 0
    uncoverenv: # beamer
      BodyStartsOnOwnLine: 0
    invisibleenv: # beamer
      BodyStartsOnOwnLine: 0

noIndentBlock:
  mintinline:
    begin: (?<!\\)\\mintinline\{
    body: '[^}]*?\}\{[^}]*?' # quote to avoid LSP error
    end: \}
