#!/bin/sh
file="$1"
w="$2"
h="$3"
# x=$4
# y=$5

case "$(file -Lb --mime-type -- "$file")" in
image/*)
    chafa -f sixel -s "${w}x${h}" --animate false -- "$file"
    exit 1
    ;;
*)
    cat "$file"
    ;;
esac
