#!/bin/sh
file="$1"
w="$2"
h="$3"
# x=$4
# y=$5

case "$(file -Lb --mime-type -- "$file")" in
image/*)
    chafa -f sixel -s "${w}x${h}" --animate off --polite on -- "$file"
    exit 1
    ;;
application/pdf)
    magick "${file}[0]" qoi:- | chafa -f sixel -s "${w}x${h}" --animate off --polite on --threshold 1 --bg white
    exit 0
    ;;
*)
    cat "$file"
    ;;
esac
